import type { CoreOption } from './types.d.ts'

export const genesisPlusGxOptions: CoreOption[] = [
  {
    name: 'genesis_plus_gx_system_hw',
    options: [
      'auto',
      'sg-1000',
      'sg-1000 II',
      'sg-1000 II + ram ext.',
      'mark-III',
      'master system',
      'master system II',
      'game gear',
      'mega drive / genesis',
    ],
    title: 'System hardware',
  },
  { name: 'genesis_plus_gx_region_detect', options: ['auto', 'ntsc-u', 'pal', 'ntsc-j'], title: 'System region' },
  { name: 'genesis_plus_gx_vdp_mode', options: ['auto', '60hz', '50hz'], title: 'Force VDP Mode' },
  {
    name: 'genesis_plus_gx_aspect_ratio',
    options: ['auto', 'NTSC PAR', 'PAL PAR', '4:3', 'Uncorrected'],
    title: 'Core-Provided Aspect Ratio',
  },
  { name: 'genesis_plus_gx_overscan', options: ['disabled', 'top/bottom', 'left/right', 'full'], title: 'Borders' },
  {
    name: 'genesis_plus_gx_left_border',
    options: ['disabled', 'left border', 'left & right borders'],
    title: 'Hide Master System Side Borders',
  },
  {
    name: 'genesis_plus_gx_gg_extra',
    options: ['disabled', 'enabled'],
    title: 'Game Gear Extended Screen',
  },
  {
    name: 'genesis_plus_gx_blargg_ntsc_filter',
    options: ['disabled', 'monochrome', 'composite', 'svideo', 'rgb'],
    title: 'Blargg NTSC Filter',
  },
  { name: 'genesis_plus_gx_lcd_filter', options: ['disabled', 'enabled'], title: 'LCD Filter' },
  { name: 'genesis_plus_gx_render', options: ['single field', 'double field'], title: 'Interlaced Mode 2 Output' },
  { name: 'genesis_plus_gx_frameskip', options: ['disabled', 'auto', 'manual'], title: 'Frameskip' },
  {
    defaultOption: '33',
    name: 'genesis_plus_gx_frameskip_threshold',
    options: ['15', '18', '21', '24', '27', '30', '33', '36', '39', '42', '45', '48', '51', '54', '57', '60'],
    title: 'Frameskip Threshold (%)',
  },
  {
    name: 'genesis_plus_gx_ym2413',
    options: ['auto', 'disabled', 'enabled'],
    title: 'Master System FM (YM2413)',
  },
  {
    name: 'genesis_plus_gx_no_sprite_limit',
    options: ['disabled', 'enabled'],
    title: 'Remove Per-Line Sprite Limit',
  },
  {
    name: 'genesis_plus_gx_enhanced_vscroll',
    options: ['disabled', 'enabled'],
    title: 'Enhanced per-tile vertical scroll',
  },
  {
    defaultOption: '8',
    name: 'genesis_plus_gx_enhanced_vscroll_limit',
    options: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
    title: 'Enhanced per-tile vertical scroll limit',
  },
  {
    name: 'genesis_plus_gx_overclock',
    options: [
      '100',
      '125',
      '150',
      '175',
      '200',
      '225',
      '250',
      '275',
      '300',
      '325',
      '350',
      '375',
      '400',
      '425',
      '450',
      '475',
      '500',
    ],
    title: 'CPU Speed',
  },
  {
    name: 'genesis_plus_gx_force_dtack',
    options: ['enabled', 'disabled'],
    title: 'System Locks-Ups',
  },
  {
    name: 'genesis_plus_gx_addr_error',
    options: ['enabled', 'disabled'],
    title: '68K Address Error',
  },
  {
    name: 'genesis_plus_gx_cd_latency',
    options: ['enabled', 'disabled'],
    title: 'CD Access Time',
  },
  {
    name: 'genesis_plus_gx_cd_precache',
    options: ['disabled', 'enabled'],
    title: 'CD Image Cache',
  },
]
