import type { CoreOption } from './types.d.ts'

export const pcsxRearmedOptions: CoreOption[] = [
  // System options
  {
    name: 'pcsx_rearmed_region',
    options: ['auto', 'NTSC', 'PAL'],
    title: 'Region',
  },
  {
    name: 'pcsx_rearmed_bios',
    options: ['auto', 'HLE'],
    title: 'BIOS Selection',
  },
  {
    name: 'pcsx_rearmed_show_bios_bootlogo',
    options: ['disabled', 'enabled', 'enabled_no_pcsx'],
    title: 'Show BIOS Boot Logo',
  },
  {
    name: 'pcsx_rearmed_memcard2',
    options: ['disabled', 'enabled'],
    title: 'Second Memory Card (Shared)',
  },
  {
    name: 'pcsx_rearmed_cd_readahead',
    options: [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '32',
      '64',
      '128',
      '256',
      '512',
      '1024',
      '333000',
    ],
    title: 'CD read-ahead',
  },
  {
    name: 'pcsx_rearmed_drc',
    options: ['disabled', 'enabled'],
    title: 'Dynamic Recompiler',
  },
  {
    name: 'pcsx_rearmed_drc_thread',
    options: ['auto', 'disabled', 'enabled'],
    title: 'DynaRec threading',
  },
  {
    defaultOption: 'auto',
    name: 'pcsx_rearmed_psxclock',
    options: [
      'auto',
      '30',
      '31',
      '32',
      '33',
      '34',
      '35',
      '36',
      '37',
      '38',
      '39',
      '40',
      '41',
      '42',
      '43',
      '44',
      '45',
      '46',
      '47',
      '48',
      '49',
      '50',
      '51',
      '52',
      '53',
      '54',
      '55',
      '56',
      '57',
      '58',
      '59',
      '60',
      '61',
      '62',
      '63',
      '64',
      '65',
      '66',
      '67',
      '68',
      '69',
      '70',
      '71',
      '72',
      '73',
      '74',
      '75',
      '76',
      '77',
      '78',
      '79',
      '80',
      '81',
      '82',
      '83',
      '84',
      '85',
      '86',
      '87',
      '88',
      '89',
      '90',
      '91',
      '92',
      '93',
      '94',
      '95',
      '96',
      '97',
      '98',
      '99',
      '100',
    ],
    title: 'PSX CPU Clock Speed (%)',
  },
  // Video options
  {
    name: 'pcsx_rearmed_dithering',
    options: ['disabled', 'enabled', 'force'],
    title: 'Dithering Pattern',
  },
  {
    name: 'pcsx_rearmed_gpu_thread_rendering',
    options: ['disabled', 'enabled'],
    title: 'Threaded Rendering',
  },
  {
    name: 'pcsx_rearmed_frameskip_type',
    options: ['disabled', 'auto', 'auto_threshold', 'fixed_interval'],
    title: 'Frameskip',
  },
  {
    defaultOption: '33',
    name: 'pcsx_rearmed_frameskip_threshold',
    options: [
      '15',
      '18',
      '21',
      '24',
      '27',
      '30',
      '33',
      '36',
      '39',
      '42',
      '45',
      '48',
      '51',
      '54',
      '57',
      '60',
      '65',
      '70',
      '75',
      '80',
    ],
    title: 'Frameskip Threshold (%)',
  },
  {
    defaultOption: '3',
    name: 'pcsx_rearmed_frameskip_interval',
    options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    title: 'Frameskip Interval',
  },
  {
    name: 'pcsx_rearmed_display_fps_v2',
    options: ['disabled', 'enabled', 'extra'],
    title: 'Display Internal FPS',
  },
  {
    name: 'pcsx_rearmed_fractional_framerate',
    options: ['auto', 'disabled', 'enabled'],
    title: 'Use fractional frame rate',
  },
  {
    name: 'pcsx_rearmed_rgb32_output',
    options: ['disabled', 'enabled'],
    title: 'RGB32 output',
  },
  {
    name: 'pcsx_rearmed_scale_hires',
    options: ['disabled', 'enabled'],
    title: 'Hi-Res Downscaling',
  },
  {
    name: 'pcsx_rearmed_gpu_slow_llists',
    options: ['auto', 'disabled', 'enabled'],
    title: '(GPU) Slow linked list processing',
  },
  {
    name: 'pcsx_rearmed_show_overscan',
    options: ['disabled', 'auto', 'hack'],
    title: '(GPU) Horizontal overscan',
  },
  {
    name: 'pcsx_rearmed_screen_centering',
    options: ['auto', 'game', 'borderless', 'manual'],
    title: '(GPU) Screen centering',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_screen_centering_x',
    options: ['-16', '-14', '-12', '-10', '-8', '-6', '-4', '-2', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    title: '(GPU) Manual position X',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_screen_centering_y',
    options: [
      '-16',
      '-15',
      '-14',
      '-13',
      '-12',
      '-11',
      '-10',
      '-9',
      '-8',
      '-7',
      '-6',
      '-5',
      '-4',
      '-3',
      '-2',
      '-1',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
    ],
    title: '(GPU) Manual position Y',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_screen_centering_h_adj',
    options: ['-64', '-48', '-40', '-32', '-24', '-16', '-8', '-7', '-6', '-5', '-4', '-3', '-2', '-1', '0'],
    title: '(GPU) Manual height adjustment',
  },
  // GPU Neon options
  {
    name: 'pcsx_rearmed_neon_interlace_enable_v2',
    options: ['auto', 'disabled', 'enabled'],
    title: '(GPU) Show Interlaced Video',
  },
  {
    name: 'pcsx_rearmed_neon_enhancement_enable',
    options: ['disabled', 'enabled'],
    title: '(GPU) Enhanced Resolution',
  },
  {
    name: 'pcsx_rearmed_neon_enhancement_no_main',
    options: ['disabled', 'enabled'],
    title: '(GPU) Enhanced Resolution Speed Hack',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_neon_enhancement_tex_adj_v2',
    options: ['disabled', 'enabled'],
    title: '(GPU) Enhanced Resolution Texture Adjustment',
  },
  // GPU PEOPS options
  {
    name: 'pcsx_rearmed_show_gpu_peops_settings',
    options: ['disabled', 'enabled'],
    title: 'Show Advanced P.E.Op.S. GPU Settings',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_odd_even_bit',
    options: ['disabled', 'enabled'],
    title: '(GPU) Odd/Even Bit Hack',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_expand_screen_width',
    options: ['disabled', 'enabled'],
    title: '(GPU) Expand Screen Width',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_ignore_brightness',
    options: ['disabled', 'enabled'],
    title: '(GPU) Ignore Brightness Color',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_disable_coord_check',
    options: ['disabled', 'enabled'],
    title: '(GPU) Disable Coordinate Check',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_lazy_screen_update',
    options: ['disabled', 'enabled'],
    title: '(GPU) Lazy Screen Update',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_repeated_triangles',
    options: ['disabled', 'enabled'],
    title: '(GPU) Repeat Flat Tex Triangles',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_quads_with_triangles',
    options: ['disabled', 'enabled'],
    title: '(GPU) Draw Tex-Quads as Triangles',
  },
  {
    name: 'pcsx_rearmed_gpu_peops_fake_busy_state',
    options: ['disabled', 'enabled'],
    title: "(GPU) Fake 'GPU Busy' States",
  },
  // GPU UNAI options
  {
    name: 'pcsx_rearmed_show_gpu_unai_settings',
    options: ['disabled', 'enabled'],
    title: 'Show Advanced UNAI GPU Settings',
  },
  {
    name: 'pcsx_rearmed_gpu_unai_old_renderer',
    options: ['disabled', 'enabled'],
    title: '(GPU) Old renderer',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_gpu_unai_blending',
    options: ['disabled', 'enabled'],
    title: '(GPU) Texture Blending',
  },
  {
    name: 'pcsx_rearmed_gpu_unai_skipline',
    options: ['disabled', 'enabled'],
    title: '(GPU) Skip every 2nd line',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_gpu_unai_lighting',
    options: ['disabled', 'enabled'],
    title: '(GPU) Lighting Effects',
  },
  {
    name: 'pcsx_rearmed_gpu_unai_fast_lighting',
    options: ['disabled', 'enabled'],
    title: '(GPU) Fast Lighting',
  },
  // Audio options
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_spu_reverb',
    options: ['disabled', 'enabled'],
    title: 'Audio Reverb Effects',
  },
  {
    defaultOption: 'simple',
    name: 'pcsx_rearmed_spu_interpolation',
    options: ['simple', 'gaussian', 'cubic', 'off'],
    title: 'Sound Interpolation',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_nocdaudio',
    options: ['disabled', 'enabled'],
    title: 'CD Audio',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_noxadecoding',
    options: ['disabled', 'enabled'],
    title: 'XA Decoding',
  },
  {
    name: 'pcsx_rearmed_spu_thread',
    options: ['disabled', 'enabled'],
    title: 'Threaded SPU',
  },
  // Input options
  {
    name: 'pcsx_rearmed_show_input_settings',
    options: ['disabled', 'enabled'],
    title: 'Show Input Settings',
  },
  {
    defaultOption: 'square',
    name: 'pcsx_rearmed_analog_axis_modifier',
    options: ['circle', 'square'],
    title: 'Analog Axis Bounds',
  },
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_vibration',
    options: ['disabled', 'enabled'],
    title: 'Rumble Effects',
  },
  {
    defaultOption: 'l1+r1+select',
    name: 'pcsx_rearmed_analog_combo',
    options: ['disabled', 'l1+r1+select', 'l1+r1+start', 'l1+r1+l3', 'l1+r1+r3', 'l3+r3'],
    title: 'DualShock Analog Mode Toggle Key Combo',
  },
  {
    name: 'pcsx_rearmed_multitap',
    options: ['disabled', 'port 1', 'port 2', 'ports 1 and 2'],
    title: 'Multitap Mode',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_negcon_deadzone',
    options: ['0', '3', '5', '7', '10', '13', '15', '17', '20', '23', '25', '27', '30'],
    title: 'NegCon Twist Deadzone',
  },
  {
    defaultOption: 'linear',
    name: 'pcsx_rearmed_negcon_response',
    options: ['linear', 'quadratic', 'cubic'],
    title: 'NegCon Twist Response',
  },
  {
    defaultOption: '1.00',
    name: 'pcsx_rearmed_input_sensitivity',
    options: [
      '0.05',
      '0.10',
      '0.15',
      '0.20',
      '0.25',
      '0.30',
      '0.35',
      '0.40',
      '0.45',
      '0.50',
      '0.55',
      '0.60',
      '0.65',
      '0.70',
      '0.75',
      '0.80',
      '0.85',
      '0.90',
      '0.95',
      '1.00',
      '1.05',
      '1.10',
      '1.15',
      '1.20',
      '1.25',
      '1.30',
      '1.35',
      '1.40',
      '1.45',
      '1.50',
      '1.55',
      '1.60',
      '1.65',
      '1.70',
      '1.75',
      '1.80',
      '1.85',
      '1.90',
      '1.95',
      '2.00',
    ],
    title: 'Mouse Sensitivity',
  },
  {
    name: 'pcsx_rearmed_crosshair1',
    options: ['disabled', 'blue', 'green', 'red', 'white'],
    title: 'Player 1 Lightgun Crosshair',
  },
  {
    name: 'pcsx_rearmed_crosshair2',
    options: ['disabled', 'blue', 'green', 'red', 'white'],
    title: 'Player 2 Lightgun Crosshair',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_konamigunadjustx',
    options: [
      '-40',
      '-39',
      '-38',
      '-37',
      '-36',
      '-35',
      '-34',
      '-33',
      '-32',
      '-31',
      '-30',
      '-29',
      '-28',
      '-27',
      '-26',
      '-25',
      '-24',
      '-23',
      '-22',
      '-21',
      '-20',
      '-19',
      '-18',
      '-17',
      '-16',
      '-15',
      '-14',
      '-13',
      '-12',
      '-11',
      '-10',
      '-9',
      '-8',
      '-7',
      '-6',
      '-5',
      '-4',
      '-3',
      '-2',
      '-1',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '26',
      '27',
      '28',
      '29',
      '30',
      '31',
      '32',
      '33',
      '34',
      '35',
      '36',
      '37',
      '38',
      '39',
      '40',
    ],
    title: 'Konami Gun X Axis Offset',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_konamigunadjusty',
    options: [
      '-40',
      '-39',
      '-38',
      '-37',
      '-36',
      '-35',
      '-34',
      '-33',
      '-32',
      '-31',
      '-30',
      '-29',
      '-28',
      '-27',
      '-26',
      '-25',
      '-24',
      '-23',
      '-22',
      '-21',
      '-20',
      '-19',
      '-18',
      '-17',
      '-16',
      '-15',
      '-14',
      '-13',
      '-12',
      '-11',
      '-10',
      '-9',
      '-8',
      '-7',
      '-6',
      '-5',
      '-4',
      '-3',
      '-2',
      '-1',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '26',
      '27',
      '28',
      '29',
      '30',
      '31',
      '32',
      '33',
      '34',
      '35',
      '36',
      '37',
      '38',
      '39',
      '40',
    ],
    title: 'Konami Gun Y Axis Offset',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_gunconadjustx',
    options: [
      '-40',
      '-39',
      '-38',
      '-37',
      '-36',
      '-35',
      '-34',
      '-33',
      '-32',
      '-31',
      '-30',
      '-29',
      '-28',
      '-27',
      '-26',
      '-25',
      '-24',
      '-23',
      '-22',
      '-21',
      '-20',
      '-19',
      '-18',
      '-17',
      '-16',
      '-15',
      '-14',
      '-13',
      '-12',
      '-11',
      '-10',
      '-9',
      '-8',
      '-7',
      '-6',
      '-5',
      '-4',
      '-3',
      '-2',
      '-1',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '26',
      '27',
      '28',
      '29',
      '30',
      '31',
      '32',
      '33',
      '34',
      '35',
      '36',
      '37',
      '38',
      '39',
      '40',
    ],
    title: 'Guncon X Axis Offset',
  },
  {
    defaultOption: '0',
    name: 'pcsx_rearmed_gunconadjusty',
    options: [
      '-40',
      '-39',
      '-38',
      '-37',
      '-36',
      '-35',
      '-34',
      '-33',
      '-32',
      '-31',
      '-30',
      '-29',
      '-28',
      '-27',
      '-26',
      '-25',
      '-24',
      '-23',
      '-22',
      '-21',
      '-20',
      '-19',
      '-18',
      '-17',
      '-16',
      '-15',
      '-14',
      '-13',
      '-12',
      '-11',
      '-10',
      '-9',
      '-8',
      '-7',
      '-6',
      '-5',
      '-4',
      '-3',
      '-2',
      '-1',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '26',
      '27',
      '28',
      '29',
      '30',
      '31',
      '32',
      '33',
      '34',
      '35',
      '36',
      '37',
      '38',
      '39',
      '40',
    ],
    title: 'Guncon Y Axis Offset',
  },
  {
    defaultOption: '1.00',
    name: 'pcsx_rearmed_gunconadjustratiox',
    options: [
      '0.75',
      '0.76',
      '0.77',
      '0.78',
      '0.79',
      '0.80',
      '0.81',
      '0.82',
      '0.83',
      '0.84',
      '0.85',
      '0.86',
      '0.87',
      '0.88',
      '0.89',
      '0.90',
      '0.91',
      '0.92',
      '0.93',
      '0.94',
      '0.95',
      '0.96',
      '0.97',
      '0.98',
      '0.99',
      '1.00',
      '1.01',
      '1.02',
      '1.03',
      '1.04',
      '1.05',
      '1.06',
      '1.07',
      '1.08',
      '1.09',
      '1.10',
      '1.11',
      '1.12',
      '1.13',
      '1.14',
      '1.15',
      '1.16',
      '1.17',
      '1.18',
      '1.19',
      '1.20',
      '1.21',
      '1.22',
      '1.23',
      '1.24',
      '1.25',
    ],
    title: 'Guncon X Axis Response',
  },
  {
    defaultOption: '1.00',
    name: 'pcsx_rearmed_gunconadjustratioy',
    options: [
      '0.75',
      '0.76',
      '0.77',
      '0.78',
      '0.79',
      '0.80',
      '0.81',
      '0.82',
      '0.83',
      '0.84',
      '0.85',
      '0.86',
      '0.87',
      '0.88',
      '0.89',
      '0.90',
      '0.91',
      '0.92',
      '0.93',
      '0.94',
      '0.95',
      '0.96',
      '0.97',
      '0.98',
      '0.99',
      '1.00',
      '1.01',
      '1.02',
      '1.03',
      '1.04',
      '1.05',
      '1.06',
      '1.07',
      '1.08',
      '1.09',
      '1.10',
      '1.11',
      '1.12',
      '1.13',
      '1.14',
      '1.15',
      '1.16',
      '1.17',
      '1.18',
      '1.19',
      '1.20',
      '1.21',
      '1.22',
      '1.23',
      '1.24',
      '1.25',
    ],
    title: 'Guncon Y Axis Response',
  },
  // Compatibility hacks
  {
    defaultOption: 'enabled',
    name: 'pcsx_rearmed_icache_emulation',
    options: ['enabled', 'disabled'],
    title: 'Instruction Cache Emulation',
  },
  {
    name: 'pcsx_rearmed_exception_emulation',
    options: ['disabled', 'enabled'],
    title: 'Exception and Breakpoint Emulation',
  },
  {
    name: 'pcsx_rearmed_cd_turbo',
    options: ['disabled', 'enabled'],
    title: 'Turbo CD',
  },
  {
    name: 'pcsx_rearmed_nocompathacks',
    options: ['disabled', 'enabled'],
    title: 'Disable Automatic Compatibility Hacks',
  },
  {
    name: 'pcsx_rearmed_nosmccheck',
    options: ['disabled', 'enabled'],
    title: '(Speed Hack) Disable SMC Checks',
  },
  {
    name: 'pcsx_rearmed_gteregsunneeded',
    options: ['disabled', 'enabled'],
    title: '(Speed Hack) Assume GTE Registers Unneeded',
  },
  {
    name: 'pcsx_rearmed_nogteflags',
    options: ['disabled', 'enabled'],
    title: '(Speed Hack) Disable GTE Flags',
  },
  {
    name: 'pcsx_rearmed_nostalls',
    options: ['disabled', 'enabled'],
    title: 'Disable CPU/GTE Stalls',
  },
]
