import type { CoreOption } from './types.d.ts'

export const fbneoOptions: CoreOption[] = [
  {
    defaultOption: 'enabled',
    name: 'fbneo-allow-depth-32',
    options: ['disabled', 'enabled'],
    title: 'Use 32-bits color depth when available',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-vertical-mode',
    options: ['disabled', 'enabled', 'alternate', 'TATE', 'TATE alternate'],
    title: 'Vertical mode',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-force-60hz',
    options: ['disabled', 'enabled'],
    title: 'Force 60Hz',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-frameskip-type',
    options: ['disabled', 'Fixed', 'Auto', 'Manual'],
    title: 'Frameskip',
  },
  {
    defaultOption: '0',
    name: 'fbneo-fixed-frameskip',
    options: ['0', '1', '2', '3', '4', '5'],
    title: 'Fixed Frameskip',
  },
  {
    defaultOption: '33',
    name: 'fbneo-frameskip-manual-threshold',
    options: ['15', '18', '21', '24', '27', '30', '33', '36', '39', '42', '45', '48', '51', '54', '57', '60'],
    title: 'Frameskip Threshold (%)',
  },
  {
    defaultOption: '100%',
    name: 'fbneo-cpu-speed-adjust',
    options: [
      '10%',
      '20%',
      '30%',
      '40%',
      '50%',
      '60%',
      '70%',
      '80%',
      '90%',
      '100%',
      '110%',
      '120%',
      '130%',
      '140%',
      '150%',
      '160%',
      '170%',
      '180%',
      '190%',
      '200%',
    ],
    title: 'CPU clock',
  },
  {
    defaultOption: 'Hold Start',
    name: 'fbneo-diagnostic-input',
    options: [
      'None',
      'Hold Start',
      'Start + A + B',
      'Hold Start + A + B',
      'Start + L + R',
      'Hold Start + L + R',
      'Hold Select',
      'Select + A + B',
      'Hold Select + A + B',
      'Select + L + R',
      'Hold Select + L + R',
    ],
    title: 'Diagnostic Input',
  },
  {
    defaultOption: 'enabled',
    name: 'fbneo-hiscores',
    options: ['disabled', 'enabled'],
    title: 'Hiscores',
  },
  {
    defaultOption: 'enabled',
    name: 'fbneo-allow-patched-romsets',
    options: ['disabled', 'enabled'],
    title: 'Allow patched romsets',
  },
  {
    defaultOption: '48000',
    name: 'fbneo-samplerate',
    options: ['44100', '48000'],
    title: 'Samplerate',
  },
  {
    defaultOption: '4-point 3rd order',
    name: 'fbneo-sample-interpolation',
    options: ['disabled', '2-point 1st order', '4-point 3rd order'],
    title: 'Sample Interpolation',
  },
  {
    defaultOption: '4-point 3rd order',
    name: 'fbneo-fm-interpolation',
    options: ['disabled', '4-point 3rd order'],
    title: 'FM Interpolation',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-lowpass-filter',
    options: ['disabled', 'enabled'],
    title: 'LowPass Filter',
  },
  {
    defaultOption: '100%',
    name: 'fbneo-analog-speed',
    options: [
      '10%',
      '20%',
      '30%',
      '40%',
      '50%',
      '60%',
      '70%',
      '80%',
      '90%',
      '100%',
      '110%',
      '120%',
      '130%',
      '140%',
      '150%',
      '160%',
      '170%',
      '180%',
      '190%',
      '200%',
    ],
    title: 'Analog Speed',
  },
  {
    defaultOption: '3',
    name: 'fbneo-socd',
    options: ['0', '1', '2', '3', '4', '5', '6'],
    title: 'SOCD Setting',
  },
  {
    defaultOption: 'hide with lightgun device',
    name: 'fbneo-lightgun-crosshair-emulation',
    options: ['hide with lightgun device', 'always hide', 'always show'],
    title: 'Crosshair emulation',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-cyclone',
    options: ['disabled', 'enabled'],
    title: 'Enable cyclone',
  },
  {
    defaultOption: 'DIPSWITCH',
    name: 'fbneo-neogeo-mode',
    options: ['DIPSWITCH', 'MVS_EUR', 'MVS_USA', 'MVS_JAP', 'AES_EUR', 'AES_JAP', 'UNIBIOS'],
    title: 'Neo-Geo mode',
  },
  {
    defaultOption: 'disabled',
    name: 'fbneo-memcard-mode',
    options: ['disabled', 'shared', 'per-game'],
    title: 'Memory card mode',
  },
]
