import type { CoreOption } from './types.d.ts'

export const fceummOptions: CoreOption[] = [
  {
    name: 'fceumm_region',
    options: ['Auto', 'NTSC', 'PAL', 'Dendy'],
    title: 'Region',
  },
  {
    name: 'fceumm_palette',
    options: [
      'default',
      'asqrealc',
      'nintendo-vc',
      'rgb',
      'yuv-v3',
      'unsaturated-final',
      'sony-cxa2025as-us',
      'pal',
      'bmf-final2',
      'bmf-final3',
      'smooth-fbx',
      'composite-direct-fbx',
      'pvm-style-d93-fbx',
      'ntsc-hardware-fbx',
      'nes-classic-fbx-fs',
      'nescap',
      'wavebeam',
      'raw',
      'custom',
    ],
    title: 'Color Palette',
  },
  {
    name: 'fceumm_turbo_enable',
    options: ['Both', 'None', 'Player 1', 'Player 2'],
    title: 'Turbo Enable',
  },
  {
    name: 'fceumm_turbo_delay',
    options: ['2', '3', '5', '10', '15', '30', '60'],
    title: 'Turbo Delay (in frames)',
  },
  {
    name: 'fceumm_up_down_allowed',
    options: ['disabled', 'enabled'],
    title: 'Allow Opposing Directions',
  },
  {
    name: 'fceumm_overscan_h',
    options: ['disabled', 'enabled'],
    title: 'Crop Overscan (Horizontal)',
  },
  {
    name: 'fceumm_overscan_v',
    options: ['disabled', 'enabled'],
    title: 'Crop Overscan (Vertical)',
  },
  {
    name: 'fceumm_sndquality',
    options: ['Low', 'High', 'Very High'],
    title: 'Sound Quality',
  },
  {
    name: 'fceumm_zapper_mode',
    options: ['clightgun', 'stlightgun', 'touchscreen', 'mouse'],
    title: 'Zapper Mode',
  },
  {
    name: 'fceumm_nospritelimit',
    options: ['disabled', 'enabled'],
    title: 'No Sprite Limit',
  },
  {
    name: 'fceumm_overclocking',
    options: ['disabled', '2x-Postrender', '2x-VBlank'],
    title: 'Overclocking',
  },
  {
    name: 'fceumm_ramstate',
    options: ['fill $ff', 'fill $00', 'random'],
    title: 'RAM power up state',
  },
  {
    name: 'fceumm_arkanoid_mode',
    options: ['mouse', 'abs_mouse', 'stelladaptor', 'touchscreen'],
    title: 'Arkanoid Mode',
  },
  {
    defaultOption: '100',
    name: 'fceumm_mouse_sensitivity',
    options: [
      '20',
      '30',
      '40',
      '50',
      '60',
      '70',
      '80',
      '90',
      '100',
      '110',
      '120',
      '130',
      '140',
      '150',
      '160',
      '170',
      '180',
      '190',
      '200',
    ],
    title: 'Mouse Sensitivity',
  },
]
