import type { CoreOption } from './types.d.ts'

export const gambatteOptions: CoreOption[] = [
  {
    name: 'gambatte_gb_colorization',
    options: ['disabled', 'auto', 'GBC', 'SGB', 'internal', 'custom'],
    title: 'GB Colorization',
  },
  {
    name: 'gambatte_gb_internal_palette',
    options: [
      'GB - DMG',
      'GB - Pocket',
      'GB - Light',
      'GBC - Blue',
      'GBC - Brown',
      'GBC - Dark Blue',
      'GBC - Dark Brown',
      'GBC - Dark Green',
      'GBC - Grayscale',
      'GBC - Green',
      'GBC - Inverted',
      'GBC - Orange',
      'GBC - Pastel Mix',
      'GBC - Red',
      'GBC - Yellow',
      'SGB - 1A',
      'SGB - 1B',
      'SGB - 1C',
      'SGB - 1D',
      'SGB - 1E',
      'SGB - 1F',
      'SGB - 1G',
      'SGB - 1H',
      'SGB - 2A',
      'SGB - 2B',
      'SGB - 2C',
      'SGB - 2D',
      'SGB - 2E',
      'SGB - 2F',
      'SGB - 2G',
      'SGB - 2H',
      'SGB - 3A',
      'SGB - 3B',
      'SGB - 3C',
      'SGB - 3D',
      'SGB - 3E',
      'SGB - 3F',
      'SGB - 3G',
      'SGB - 3H',
      'SGB - 4A',
      'SGB - 4B',
      'SGB - 4C',
      'SGB - 4D',
      'SGB - 4E',
      'SGB - 4F',
      'SGB - 4G',
      'SGB - 4H',
      'Special 1',
      'Special 2',
      'Special 3',
      'Special 4 (TI-83 Legacy)',
      'TWB64 - Pack 1',
      'TWB64 - Pack 2',
      'TWB64 - Pack 3',
      'PixelShift - Pack 1',
    ],
    title: 'Internal Palette',
  },
  {
    name: 'gambatte_gbc_color_correction',
    options: ['GBC only', 'always', 'disabled'],
    title: 'Color Correction',
  },
  {
    name: 'gambatte_gbc_color_correction_mode',
    options: ['accurate', 'fast'],
    title: 'Color Correction Mode',
  },
  {
    name: 'gambatte_gbc_frontlight_position',
    options: ['central', 'above screen', 'below screen'],
    title: 'Color Correction - Frontlight Position',
  },
  {
    name: 'gambatte_dark_filter_level',
    options: ['0', '5', '10', '15', '20', '25', '30', '35', '40', '45', '50'],
    title: 'Dark Filter Level (%)',
  },
  {
    name: 'gambatte_mix_frames',
    options: ['disabled', 'mix', 'lcd_ghosting', 'lcd_ghosting_fast'],
    title: 'Interframe Blending',
  },
  {
    name: 'gambatte_audio_resampler',
    options: ['sinc', 'cc'],
    title: 'Audio Resampler',
  },
  {
    name: 'gambatte_gb_hwmode',
    options: ['Auto', 'GB', 'GBC', 'GBA'],
    title: 'Emulated Hardware',
  },
  {
    name: 'gambatte_gb_bootloader',
    options: ['enabled', 'disabled'],
    title: 'Use Official Bootloader',
  },
  {
    name: 'gambatte_turbo_period',
    options: ['4', '5', '6', '7', '8', '9', '10'],
    title: 'Turbo Button Period',
  },
  {
    name: 'gambatte_rumble_level',
    options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    title: 'Controller Rumble Strength',
  },
]
