import type { CoreOption } from './types.d.ts'

export const mame2003PlusOptions: CoreOption[] = [
  {
    name: 'mame2003-plus_four_way_emulation',
    options: ['disabled', 'enabled'],
    title: '4-way joystick emulation on 8-way joysticks',
  },
  {
    name: 'mame2003-plus_mouse_device',
    options: ['mouse', 'pointer', 'disabled'],
    title: 'Skip Disclaimer',
  },
  {
    name: 'mame2003-plus_skip_disclaimer',
    options: ['enabled', 'disabled'],
    title: 'Skip Disclaimer',
  },
  {
    name: 'mame2003-plus_skip_warnings',
    options: ['enabled', 'disabled'],
    title: 'Skip Warnings',
  },
  {
    name: 'mame2003-plus_display_setup',
    options: ['disabled', 'enabled'],
    title: 'Display MAME menu',
  },
  {
    defaultOption: '1.0',
    name: 'mame2003-plus_brightness',
    options: [
      '0.2',
      '0.3',
      '0.4',
      '0.5',
      '0.6',
      '0.7',
      '0.8',
      '0.9',
      '1.0',
      '1.1',
      '1.2',
      '1.3',
      '1.4',
      '1.5',
      '1.6',
      '1.7',
      '1.8',
      '1.9',
      '2.0',
    ],
    title: 'Brightness',
  },
  {
    name: 'mame2003-plus_gamma',
    options: [
      '0.5',
      '0.6',
      '0.7',
      '0.8',
      '0.9',
      '1.0',
      '1.1',
      '1.2',
      '1.3',
      '1.4',
      '1.5',
      '1.6',
      '1.7',
      '1.8',
      '1.9',
      '2.0',
    ],
    title: 'Gamma Correction',
  },
  {
    name: 'mame2003-plus_display_artwork',
    options: ['enabled', 'disabled'],
    title: 'Display Artwork',
  },
  {
    name: 'mame2003-plus_art_resolution',
    options: ['1', '2', '3', '4', '5', '6', '7', '8'],
    title: 'Artwork Resolution Multiplier',
  },
  {
    name: 'mame2003-plus_art_overlay_opacity',
    options: [
      'default',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '50',
      '70',
    ],
    title: 'Artwork Hardcoded Overlay Opacity',
  },
  {
    name: 'mame2003-plus_neogeo_bios',
    options: [
      'default',
      'euro',
      'euro-s1',
      'us',
      'us-e',
      'asia',
      'japan',
      'japan-s2',
      'unibios33',
      'unibios20',
      'unibios13',
      'unibios11',
      'unibios10',
      'debug',
      'asia-aes',
    ],
    title: 'Specify Neo Geo BIOS (Restart core)',
  },
  {
    name: 'mame2003-plus_stv_bios',
    options: ['default', 'japan', 'japana', 'us', 'japan_b', 'taiwan', 'europe'],
    title: 'Specify Sega ST-V BIOS',
  },
  {
    name: 'mame2003-plus_use_samples',
    options: ['enabled', 'disabled'],
    title: 'Use Samples',
  },
  {
    name: 'mame2003-plus_use_alt_sound',
    options: ['disabled', 'enabled'],
    title: 'Use CD Soundtrack',
  },
  {
    name: 'mame2003-plus_use_dialsharexy',
    options: ['disabled', 'enabled'],
    title: 'Share 2 Player Dial Controls Across One X/Y Device',
  },
  {
    name: 'mame2003-plus_dial_swap_xy',
    options: ['disabled', 'enabled'],
    title: 'Swap X and Y Dial Axis',
  },
  {
    name: 'mame2003-plus_tate_mode',
    options: ['disabled', 'enabled'],
    title: 'TATE Mode',
  },
  {
    defaultOption: '1024x768',
    name: 'mame2003-plus_vector_resolution',
    options: ['640x480', '1024x768', '1280x960', '1440x1080', '1600x1200', '1707x1280', 'original'],
    title: 'Vector Resolution',
  },
  {
    name: 'mame2003-plus_vector_antialias',
    options: ['enabled', 'disabled'],
    title: 'Vector Antialiasing',
  },
  {
    name: 'mame2003-plus_nvram_bootstraps',
    options: ['enabled', 'disabled'],
    title: 'NVRAM Bootstraps',
  },
  {
    defaultOption: '48000',
    name: 'mame2003-plus_sample_rate',
    options: ['8000', '11025', '22050', '30000', '44100', '48000'],
    title: 'Sample Rate',
  },
  {
    defaultOption: 'simultaneous',
    name: 'mame2003-plus_input_interface',
    options: ['simultaneous', 'retropad', 'keyboard'],
    title: 'Input Interface',
  },
  {
    defaultOption: 'disabled',
    name: 'mame2003-plus_frameskip',
    options: [
      'disabled',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      'auto',
      'auto_aggressive',
      'auto_max',
    ],
    title: 'Frameskip',
  },
  {
    name: 'mame2003-plus_cpu_clock_scale',
    options: [
      'default',
      '25',
      '30',
      '35',
      '40',
      '45',
      '50',
      '55',
      '60',
      '65',
      '70',
      '75',
      '80',
      '85',
      '90',
      '95',
      '105',
      '110',
      '115',
      '120',
      '125',
      '200',
      '250',
      '300',
    ],
    title: 'CPU Clock Scale',
  },
  {
    name: 'mame2003-plus_override_ad_stick',
    options: ['disabled', 'enabled'],
    title: 'Use Lightgun as an Analog Stick',
  },
  {
    name: 'mame2003-plus_input_toggle',
    options: ['enabled', 'disabled'],
    title: 'Allow Input Button to Act as a Toggle Switch',
  },
]
