import type { CoreOption } from './types.d.ts'

export const mednafenWswanOptions: CoreOption[] = [
  {
    name: 'wswan_rotate_display',
    options: ['manual', 'landscape', 'portrait'],
    title: 'Display Rotation',
  },
  {
    name: 'wswan_rotate_keymap',
    options: ['auto', 'disabled', 'enabled'],
    title: 'Rotate Button Mappings',
  },
  {
    name: 'wswan_mono_palette',
    options: [
      'default',
      'wonderswan',
      'wondeswan_color',
      'swancrystal',
      'gb_dmg',
      'gb_pocket',
      'gb_light',
      'blossom_pink',
      'bubbles_blue',
      'buttercup_green',
      'digivice',
      'game_com',
      'gameking',
      'game_master',
      'golden_wild',
      'greenscale',
      'hokage_orange',
      'labo_fawn',
      'legendary_super_saiyan',
      'microvision',
      'million_live_gold',
      'odyssey_gold',
      'shiny_sky_blue',
      'slime_blue',
      'ti_83',
      'travel_wood',
      'virtual_boy',
    ],
    title: 'Color Palette',
  },
  {
    name: 'wswan_gfx_colors',
    options: ['16bit', '24bit'],
    title: 'Color Depth',
  },
  { name: 'wswan_60hz_mode', options: ['disabled', 'enabled'], title: '60Hz Mode' },
  {
    defaultOption: '44100',
    name: 'wswan_sound_sample_rate',
    options: ['11025', '22050', '44100', '48000'],
    title: 'Sound Output Sample Rate',
  },
  {
    name: 'wswan_sound_low_pass',
    options: ['disabled', 'enabled'],
    title: 'Audio Filter',
  },
]
