import type { CoreOption } from './types.d.ts'

export const mgbaOptions: CoreOption[] = [
  {
    name: 'mgba_solar_sensor_level',
    options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    title: 'Solar Sensor Level',
  },
  {
    name: 'mgba_allow_opposing_directions',
    options: ['no', 'yes'],
    title: 'Allow Opposing Directional Input',
  },
  {
    name: 'mgba_gb_model',
    options: ['Autodetect', 'Game Boy', 'Super Game Boy', 'Game Boy Color', 'Game Boy Advance'],
    title: 'Game Boy Model',
  },
  {
    name: 'mgba_force_gbp',
    options: ['OFF', 'ON'],
    title: 'Game Boy Player Rumble',
  },
  {
    name: 'mgba_idle_optimization',
    options: ['Remove Known', 'Detect and Remove', "Don't Remove"],
    title: 'Idle Loop Removal',
  },
  {
    name: 'mgba_frameskip',
    options: ['disabled', 'auto', 'auto_threshold', 'fixed_interval'],
    title: 'Frameskip',
  },
  {
    defaultOption: '33',
    name: 'mgba_frameskip_threshold',
    options: ['15', '18', '21', '24', '27', '30', '33', '36', '39', '42', '45', '48', '51', '54', '57', '60'],
    title: 'Frameskip Threshold (%)',
  },
  {
    name: 'mgba_frameskip_interval',
    options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    title: 'Frameskip Interval',
  },
  {
    name: 'mgba_use_bios',
    options: ['ON', 'OFF'],
    title: 'Use BIOS File if Found',
  },
  {
    defaultOption: 'DMG Green',
    name: 'mgba_gb_colors',
    options: [
      'Grayscale',
      'DMG Green',
      'GB Pocket',
      'GB Light',
      'GBC Brown ↑',
      'GBC Red ↑A',
      'GBC Dark Brown ↑B',
      'GBC Pale Yellow ↓',
      'GBC Orange ↓A',
      'GBC Yellow ↓B',
      'GBC Blue ←',
      'GBC Dark Blue ←A',
      'GBC Gray ←B',
      'GBC Green →',
      'GBC Dark Green →A',
      'GBC Reverse →B',
      'SGB 1-A',
      'SGB 1-B',
      'SGB 1-C',
      'SGB 1-D',
      'SGB 1-E',
      'SGB 1-F',
      'SGB 1-G',
      'SGB 1-H',
      'SGB 2-A',
      'SGB 2-B',
      'SGB 2-C',
      'SGB 2-D',
      'SGB 2-E',
      'SGB 2-F',
      'SGB 2-G',
      'SGB 2-H',
      'SGB 3-A',
      'SGB 3-B',
      'SGB 3-C',
      'SGB 3-D',
      'SGB 3-E',
      'SGB 3-F',
      'SGB 3-G',
      'SGB 3-H',
      'SGB 4-A',
      'SGB 4-B',
      'SGB 4-C',
      'SGB 4-D',
      'SGB 4-E',
      'SGB 4-F',
      'SGB 4-G',
      'SGB 4-H',
    ],
    title: 'Default Game Boy Palette',
  },
  {
    name: 'mgba_skip_bios',
    options: ['ON', 'OFF'],
    title: 'Skip BIOS Intro',
  },
  {
    name: 'mgba_gb_colors_preset',
    options: ['0', '1', '2', '3'],
    title: 'Hardware Preset Game Boy Palettes',
  },
  {
    name: 'mgba_sgb_borders',
    options: ['ON', 'OFF'],
    title: 'Use Super Game Boy Borders',
  },
  {
    name: 'mgba_color_correction',
    options: ['OFF', 'GBA', 'GBC', 'Auto'],
    title: 'Color Correction',
  },
  {
    name: 'mgba_interframe_blending',
    options: ['OFF', 'mix', 'mix_smart', 'lcd_ghosting', 'lcd_ghosting_fast'],
    title: 'Interframe Blending',
  },
]
