import type { CoreOption } from './types.d.ts'

export const snes9xOptions: CoreOption[] = [
  { name: 'snes9x_up_down_allowed', options: ['disabled', 'enabled'], title: 'Allow Opposing Directions' },
  { name: 'snes9x_region', options: ['auto', 'ntsc', 'pal'], title: 'Console region (Reload core)' },
  {
    name: 'snes9x_overclock_superfx',
    options: [
      '50%',
      '60%',
      '70%',
      '80%',
      '90%',
      '100%',
      '150%',
      '200%',
      '250%',
      '300%',
      '350%',
      '400%',
      '450%',
      '500%',
    ],
    title: 'SuperFX Frequency',
  },
  {
    name: 'snes9x_overclock_cycles',
    options: ['disabled', 'light', 'compatible', 'max'],
    title: 'Reduce Slowdown (Hack, Unsafe)',
  },
  {
    name: 'snes9x_reduce_sprite_flicker',
    options: ['disabled', 'enabled'],
    title: 'Reduce Flickering (Hack, Unsafe)',
  },
  {
    name: 'snes9x_randomize_memory',
    options: ['disabled', 'enabled'],
    title: 'Randomize Memory (Unsafe)',
  },
  {
    name: 'snes9x_hires_blend',
    options: ['disabled', 'merge', 'blur'],
    title: 'Hires Blending',
  },
  {
    name: 'snes9x_blargg',
    options: ['disabled', 'monochrome', 'rf', 'composite', 's-video', 'rgb'],
    title: 'Blargg NTSC filter',
  },
  { name: 'snes9x_overscan', options: ['enabled', 'disabled', 'auto'], title: 'Crop overscan' },
  { name: 'snes9x_aspect', options: ['4:3', 'uncorrected', 'auto', 'ntsc', 'pal'], title: 'Preferred aspect ratio' },
  {
    defaultOption: '2',
    name: 'snes9x_superscope_crosshair',
    options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
    title: 'Super Scope crosshair',
  },
  {
    name: 'snes9x_superscope_color',
    options: [
      'White',
      'White (blend)',
      'Red',
      'Red (blend)',
      'Orange',
      'Orange (blend)',
      'Yellow',
      'Yellow (blend)',
      'Green',
      'Green (blend)',
      'Cyan',
      'Cyan (blend)',
      'Sky',
      'Sky (blend)',
      'Blue',
      'Blue (blend)',
      'Violet',
      'Violet (blend)',
      'Pink',
      'Pink (blend)',
      'Purple',
      'Purple (blend)',
      'Black',
      'Black (blend)',
      '25% Grey',
      '25% Grey (blend)',
      '50% Grey',
      '50% Grey (blend)',
      '75% Grey',
      '75% Grey (blend)',
    ],
    title: 'Super Scope color',
  },
  {
    name: 'snes9x_block_invalid_vram_access',
    options: ['enabled', 'disabled'],
  },
]
